builds:
- env:
    - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - 386
  - amd64
  - arm
  - arm64
  goarm:
  - "6"
  main: .
  binary: edic
  hooks: {}
archive:
  name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  replacements:
    darwin: macOS
    linux: inux
    windows: windows
    386: i386
    amd64: x86_64
  format_overrides:
  - goos: windows
    format: zip
  files:
  - LICENSE*
  - README*
  - CHANGELOG*
  - docs
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}

