language: go
sudo: true
notifications:
  email: true
go:
  - 1.11.x

before_install:
  - go get -u golang.org/x/lint/golint
    #- go get github.com/golangci/golangci-lint/cmd/golangci-lint

script:
    #- golangci-lint run       # run a bunch of code checkers/linters in parallel
  - go vet ./...
  - golint -set_exit_status $(go list ./...)

after_success:
  - bash <(curl -s https://codecov.io/bash)
